// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SnowflakeClient is the client API for Snowflake service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SnowflakeClient interface {
	// 获得分布式ID
	GetID(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetIDResp, error)
	// 每分钟同一来源IP只能被获取两次分布式ID
	GetIDByRateLimit(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetIDResp, error)
}

type snowflakeClient struct {
	cc grpc.ClientConnInterface
}

func NewSnowflakeClient(cc grpc.ClientConnInterface) SnowflakeClient {
	return &snowflakeClient{cc}
}

func (c *snowflakeClient) GetID(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetIDResp, error) {
	out := new(GetIDResp)
	err := c.cc.Invoke(ctx, "/webtest.snowflake/GetID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snowflakeClient) GetIDByRateLimit(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetIDResp, error) {
	out := new(GetIDResp)
	err := c.cc.Invoke(ctx, "/webtest.snowflake/GetIDByRateLimit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SnowflakeServer is the server API for Snowflake service.
// All implementations must embed UnimplementedSnowflakeServer
// for forward compatibility
type SnowflakeServer interface {
	// 获得分布式ID
	GetID(context.Context, *emptypb.Empty) (*GetIDResp, error)
	// 每分钟同一来源IP只能被获取两次分布式ID
	GetIDByRateLimit(context.Context, *emptypb.Empty) (*GetIDResp, error)
	mustEmbedUnimplementedSnowflakeServer()
}

// UnimplementedSnowflakeServer must be embedded to have forward compatible implementations.
type UnimplementedSnowflakeServer struct {
}

func (UnimplementedSnowflakeServer) GetID(context.Context, *emptypb.Empty) (*GetIDResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetID not implemented")
}
func (UnimplementedSnowflakeServer) GetIDByRateLimit(context.Context, *emptypb.Empty) (*GetIDResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIDByRateLimit not implemented")
}
func (UnimplementedSnowflakeServer) mustEmbedUnimplementedSnowflakeServer() {}

// UnsafeSnowflakeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SnowflakeServer will
// result in compilation errors.
type UnsafeSnowflakeServer interface {
	mustEmbedUnimplementedSnowflakeServer()
}

func RegisterSnowflakeServer(s grpc.ServiceRegistrar, srv SnowflakeServer) {
	s.RegisterService(&Snowflake_ServiceDesc, srv)
}

func _Snowflake_GetID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnowflakeServer).GetID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webtest.snowflake/GetID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnowflakeServer).GetID(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Snowflake_GetIDByRateLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnowflakeServer).GetIDByRateLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webtest.snowflake/GetIDByRateLimit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnowflakeServer).GetIDByRateLimit(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Snowflake_ServiceDesc is the grpc.ServiceDesc for Snowflake service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Snowflake_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "webtest.snowflake",
	HandlerType: (*SnowflakeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetID",
			Handler:    _Snowflake_GetID_Handler,
		},
		{
			MethodName: "GetIDByRateLimit",
			Handler:    _Snowflake_GetIDByRateLimit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "snowflake.proto",
}
